<script>
alert("bienvenidos")
</script>
<html>

<script>
alert("continuar viendo la pagina")
</script>

<script>
alert("ver tabla")
</script>
<HTML>
<HEAD>
<TITLE>PROGRAMA 70</TITLE>
</HEAD>
<BODY BGCOLOR=#ffC0CB>
<h1><FONT COLOR=#00FFFF FONT=SCRIPT SIZE=9>TABLAS </h1>
<h2><FONT COLOR=#00FFFF FONT=SCRIPT SIZE=9>se siempre tu mejor version</h2>
<TABLE BORDER="1">
<thead>
<tr>
<th BGCOLOR=MAGENTA>P31</th>
<td><A HREF=E:\PROGRAMAS1-20\P1.HTML>NOMBRE</A> 
<BR><img src=E:/GIF/1g.gif HEIGHT="40" WIDTH="40"></td>
 </tr>
</script>
</BODY>
</FONT>
</IMG>
</HTML>

<script>
alert("escuchar CULPABLES-MANUEL TURIZO")
</script>
<HTML>
<HEAD>
<TITLE>PROGRAMA 51</TITLE>
<BODY BGCOLOR=PALEGREEN>
<TABLE BORDER=1>
<TR>
<TH><FONT COLOR=#FF00FF FONT=SCRIPT SIZE=20> AUDIO 1 </TH>
<TH><FONT COLOR=BLACK SCRIPT=ARIAL SIZE=60><MARQUEE DIRECTION=UP LOOP=40 SCROLLAMOUNT=10>culpables manuel turizo</TH>
</TR>
<AUDIO CONTROLS>
<source src=E:/audvud/culpables.mp3 type=audio/mp3>
</source>
</AUDIO>
</BODY>
</HTML>
<script>
alert("ver programa 56")
</script>
<HTML>
<HEAD>
<TITLE>PROGRAMA 56</TITLE>
<BODY BGCOLOR=darkgray>
<TABLE BORDER=1>
<TR>
<TH><FONT COLOR=#BA55D3 FONT=SCRIPT SIZE=10> VIDEO 1 </TH>
<TH><FONT COLOR=BLACK SCRIPT=ARIAL SIZE=60><MARQUEE DIRECTION=UP LOOP=30 SCROLLAMOUNT=6><i> CARTA BONITA</i></TH>
</TR>
</MARQUEE>
</BODY>
<VIDEO WIDTH="550" HEIGHT="490" CONTROLS AUTOPLAY>
<source src=E:/audvud/carta.mp4 type=video/mp4>
</VIDEO>
<TABLE BORDER=1>
<TR>
<TH><FONT COLOR=#20B2AA FONT=SCRIPT SIZE=20> AUDIO 1 </TH>
<TH><FONT COLOR=BLACK SCRIPT=ARIAL SIZE=60><MARQUEE DIRECTION=DOWN LOOP=40 SCROLLAMOUNT=10><B>culpables manuel turizo</B></TH>
</TR>
<IMG SRC=E:/audvud/CUTE.gif HEIGHT="130" WIDTH="98">
<AUDIO CONTROLS>
<source src=E:/audvud/culpables.mp3 type=audio/mp3>
</source>
</AUDIO>
</BODY>
</HTML>

<script>
alert("ver videos")
</script>
<HTML>
<HEAD>
<TITLE>PROGRAMA 60</TITLE>
<BODY BGCOLOR=#DB7093>
<VIDEO WIDTH="450" HEIGHT="390" CONTROLS AUTOPLAY>
<SOURCE SRC=E:/audvud/HTODO.mp4 type=video/mp4>
</SOURCE>
</VIDEO>
<TABLE BORDER=1>
<TR>
<TH><FONT COLOR=#FF00FF FONT=SCRIPT SIZE=20> AUDIO 1 </TH>
<TH><FONT COLOR=BLACK SCRIPT=ARIAL SIZE=60><MARQUEE DIRECTION=UP LOOP=80 SCROLLAMOUNT=10>culpables manuel turizo</TH>
<TH><FONT COLOR=#000080 SCRIPT=ARIAL SIZE=55>VIDEO1</TH>
<TH><FONT COLOR=PINK SCRIPT=ARIAL SIZE=55><MARQUEE DIRECTION=RIGHT LOOP=80 SCROLLAMOUNT=10>HELLO KITTY</TH>
</TR>
<IMG SRC=E:/audvud/CUTE.gif HEIGHT="100" WIDTH="75">
<AUDIO CONTROLS>
<SOURCE SRC=E:/audvud/culpables.mp3 type=audio/mp3>
</source>
</AUDIO>
</BODY>
<script>
alert(" ver video entrega especial")
</script>
</HTML>

<TABLE BORDER=1>
<TR>
<TH><FONT COLOR=BLACK FONT=SCRIPT SIZE=20 FONT BGCOLOR=PINK > AUDIO 2 </TH>
<TH><FONT COLOR=#AQUA SCRIPT=ARIAL SIZE=60><MARQUEE DIRECTION=LEFT LOOP=40 SCROLLAMOUNT=10>MARKITOS</TH>
<TH><FONT COLOR=BLACK SCRIPT=ARIAL SIZE=55>VIDEO2</TH>
<TH><FONT COLOR=PINK SCRIPT=ARIAL SIZE=55><MARQUEE DIRECTION=UP LOOP=40 SCROLLAMOUNT=5>ENTREGA ESPECIAL</TH>
</TR>
<IMG SRC=E:/audvud/HOME.gif HEIGHT="150" WIDTH="111">
<AUDIO CONTROLS>
<SOURCE SRC=E:/audvud/markitos.mp3 type=audio/mp3>
</source>
</AUDIO>
<VIDEO WIDTH="450" HEIGHT="380" CONTROLS >
<SOURCE SRC=E:/audvud/HENTREGA.mp4 type=video/mp4>
</SOURCE>
</VIDEO>
</BODY>

<script>
alert("ver chapuzon")
</script>
</HTML>
<TABLE BORDER=1>
<TR>
<TH><FONT COLOR=#E9967A FONT=SCRIPT SIZE=20 FONT BGCOLOR=PINK > AUDIO 3 </TH>
<TH><FONT COLOR=ORANGE SCRIPT=ARIAL SIZE=60><MARQUEE DIRECTION=DOWN LOOP=40 SCROLLAMOUNT=10>TUS MENTIRAS</TH>
<TH><FONT COLOR=PINK SCRIPT=ARIAL SIZE=55>VIDEO 3</TH>
<TH><FONT COLOR=BLACK SCRIPT=ARIAL SIZE=55><MARQUEE DIRECTION=RIGHT LOOP=40 SCROLLAMOUNT=5>CHAPUZON</TH>
</TR>
<IMG SRC=E:/audvud/POLLO.gif HEIGHT="370" WIDTH="211">
<AUDIO CONTROLS>
<SOURCE SRC=E:/audvud/MENTIS.mp3 type=audio/mp3>
</source>
</AUDIO>
<VIDEO WIDTH="550" HEIGHT="390" CONTROLS >
<source src=E:/audvud/CHAPUZON.mp4 type=video/mp4>
</SOURCE>
</VIDEO>
</BODY>
<script>
alert("ver alistandome video")
</script>
</HTML>
<TABLE BORDER=1>
<TR>
<TH><FONT COLOR=BLACK FONT=SCRIPT SIZE=20 FONT BGCOLOR=PINK > AUDIO 4 </TH>
<TH><FONT COLOR=MAGENTA SCRIPT=ARIAL SIZE=60><MARQUEE DIRECTION=DOWN LOOP=40 SCROLLAMOUNT=10>TUS MENTIRAS</TH>
<TH><FONT COLOR=NAVY SCRIPT=ARIAL SIZE=55>VIDEO 4</TH>
<TH><FONT COLOR=BLACK SCRIPT=ARIAL SIZE=55><MARQUEE DIRECTION=LEFT LOOP=40 SCROLLAMOUNT=5>ALISTANDOME</TH>
</TR>
<IMG SRC=E:/audvud/RATA.gif HEIGHT="190" WIDTH="211">
<AUDIO CONTROLS>
<source src=E:/audvud/RELSB.mp3 type=audio/mp3>
</source>
</AUDIO>
<VIDEO WIDTH="460" HEIGHT="390" CONTROLS >
<SOURCE SRC=E:/audvud/GRWM.mp4 type=video/mp4>
</SOURCE>
</VIDEO>
</BODY>
<script>
alert("acceder a todos el sitio")
</script>
</HTML>
<TABLE BORDER=1>
<TR>
<TH><FONT COLOR=BLACK FONT=SCRIPT SIZE=20 FONT BGCOLOR=PINK > AUDIO 5 </TH>
<TH><FONT COLOR=MAGENTA SCRIPT=ARIAL SIZE=60><MARQUEE DIRECTION=DOWN LOOP=40 SCROLLAMOUNT=10>TUS MENTIRAS</TH>
<TH><FONT COLOR=NAVY SCRIPT=ARIAL SIZE=55>VIDEO 5</TH>
<TH><FONT COLOR=BLACK SCRIPT=ARIAL SIZE=55><MARQUEE DIRECTION=LEFT LOOP=40 SCROLLAMOUNT=5>INVIERNO</TH>
</TR>
<IMG SRC=E:/audvud/RATA.gif HEIGHT="190" WIDTH="211">
<AUDIO CONTROLS>
<SOURCE SRC=E:/audvud/RELSB.mp3 type=audio/mp3>
</source>
</AUDIO>
<VIDEO WIDTH="460" HEIGHT="390" CONTROLS >
<SOURCE SRC=E:/audvud/INVIERNO.mp4 type=video/mp4>
</SOURCE>
</VIDEO>
</BODY>
</HTML>










